apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fastfood-deployment
  namespace: namespace-fastfood
  labels:
    app: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood
  template:
    metadata:
      labels:
        app: fastfood
    spec:
      containers:
        - name: app-fastfood
          image: localhost:5000/fastfood-clean-arch
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: JPA_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-fastfood-configmap
                  key: datasource_url
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: datasource_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: datasource_password
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livelinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10