apiVersion: v1
kind: Service
metadata:
  name: app-fastfood-service
  namespace: namespace-fastfood
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: fastfood