apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
  namespace: namespace-fastfood
data:
  postgres_root_password: root
  postgres_user: root
  postgres_password: root
  datasource_username: admin
  datasource_password: postgres
